name: Check Pull Request Source

on:
  pull_request:
    types: [edited, labeled, opened, reopened, synchronize, unlabeled]
    branches:
      - main
      - staging

jobs:
  check:
    name: Check Pull Reqest Source
    runs-on: ubuntu-latest
    steps:
      - name: Check title and label
        uses: actions/github-script@v5
        with:
          script: |
            console.log('repo source details', context)
            const errorMessage = ''
            // Check title
            const title = context.payload.pull_request.title
            const prefix = title.split('-')[0]
            console.log('prefix', prefix)
            if (!['fix', 'modify', 'feature', 'breaking'].includes(prefix)) {
              errorMessage.concat('Prefix must be fix|modify|feature|breaking')
            }
            // Check label if base branch is staging
            console.log('head', context.payload.pull_request.head)
            console.log('base', context.payload.pull_request.base)
            const labels = context.payload.pull_request.labels
            console.log('labels', labels)
            if (!labels.includes('QAPassed')) {
              errorMessage.concat(', must have label QA passed')
            }
            console.log('errorMessage', errorMessage)
            if (errorMessage) {
              core.setFailed(errorMessage)
            }
