name: Create or Update Pull Request Release

on:
  push:
    branches:
      - staging

jobs:
  check:
    name: Create or update pull request release
    runs-on: ubuntu-latest
    steps:
      - name: Check should create / update
        uses: actions/github-script@v5
        with:
          script: |
            // Check if there is no changes between branch staging and main
            const repoMainData = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
            })
            const repoStagingData = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'staging',
            })
            console.log('repoMainData', repoMainData)
            console.log('repoMainData commit', repoMainData.data.commit.commit)
            console.log('repoStagingData', repoStagingData)

            // Skip Create / Update Pull Request
            if (repoMainData.data.commit.sha === repoStagingData.data.commit.sha) {
              return {
                skipCreatePullRequest: false,
              }
            }

            // Check create / update
            // get list of merged PR
            const pullRequestsStaging = await github.rest.pulls.list({
              owner: context.actor,
              repo: context.repo.repo,
              state: 'closed',
              base: 'staging',
              sort: 'updated',
            })
            const pullRequestsStagingMerged = pullRequestsStaging.data.filter((pullRequest) => 
              !!pullRequest.merged_at
              // open when no development changing from main
              // && new Date(pullRequest.merged_at) > new Date(context.payload.pull_request.base.updated_at)
            )

            if (pullRequestsStagingMerged.length === 0) {
              // Create
              const today = new Date().toDateString()
              const createdPR = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: 'staging',
                base: 'main',
                title: `Release - ${today}`,
                body: `
                ## Fix:
                ## Feature:
                ## Modify:
                ## Breaking:
                `
              })
              console.log('createdPR', createdPR)
              return createdPR
            }

            // Update
            // Get Pull Request Release
            // get list of merged PR
            const pullRequestsReleases = await github.rest.pulls.list({
              owner: context.actor,
              repo: context.repo.repo,
              state: 'open',
              base: 'main',
              sort: 'updated',
            })
            const pullRequestsRelease = pullRequestsReleases.data[0]

            // Generate and update pull request body
            const mappedTitle = (str) => {
              const prefix = str.split('-')[0].trim().toLowerCase()
              return {
                prType: prefix,
                title: str,
              }
            }
            let body = ''
            const titles = pullRequestsStagingMerged.map((item) => ({
              ...mappedTitle(item.title),
              url: item.url,
            }))
            console.log('titles', titles)
            const listTypes = ['feature', 'fix', 'breaking', 'modify']
            console.log('listTypes', listTypes)
            listTypes.forEach((prType) => {
              console.log('prType', prType)
              body += `\n## ${prType}`
              const titleTypes = titles.filter((title) => title.prType === prType)
              titleTypes.forEach((titleType) => {
                body += `\n - ${titleType.title} [url](${titleType.url})`
              })
            })
            console.log('body', body)
            await github.rest.pulls.update({
              owner: context.actor,
              repo: context.repo.repo,
              pull_number: pullRequestsRelease.number,
              body,
            });

            return {
              skipCreatePullRequest: true,
            }
