name: Create Pull Request Release

on:
  release:
    types: [published]

jobs:
  create:
    name: Create pull request release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Create Pull Request
        uses: actions/github-script@v5
        env:
          TAG_LATEST: ${{ steps.previoustag.outputs.tag }}
        with:
          script: |
            console.log('TAG_LATEST', process.env.TAG_LATEST)
            console.log('context', context)
            const script = require('./scriptGithub/createPullRequest.js')
            script({github, exec, context})